/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseChart: typeof import('./src/components/charts/BaseChart.vue')['default']
    CustomerAnalysisChart: typeof import('./src/components/charts/CustomerAnalysisChart.vue')['default']
    DataImportChart: typeof import('./src/components/charts/DataImportChart.vue')['default']
    FinancialAnalysisChart: typeof import('./src/components/charts/FinancialAnalysisChart.vue')['default']
    MarketAnalysisChart: typeof import('./src/components/charts/MarketAnalysisChart.vue')['default']
    ProductAnalysisChart: typeof import('./src/components/charts/ProductAnalysisChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemMonitorChart: typeof import('./src/components/charts/SystemMonitorChart.vue')['default']
  }
}
