version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: bmos_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./database/clickhouse/schema:/docker-entrypoint-initdb.d
      - ./database/clickhouse/config:/etc/clickhouse-server/config.d
    environment:
      CLICKHOUSE_DB: bmos
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - bmos_network

  redis:
    image: redis:7-alpine
    container_name: bmos_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - bmos_network

  backend:
    build: ./backend
    container_name: bmos_backend
    ports:
      - "8000:8000"
    depends_on:
      - clickhouse
      - redis
    environment:
      CLICKHOUSE_URL: clickhouse://default:@clickhouse:8123/bmos
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: mysql://root:password@mysql:3306/qbm_ai_system
    volumes:
      - ./backend:/app
      - ./models:/app/models
    networks:
      - bmos_network

  celery:
    build: ./backend
    container_name: bmos_celery
    command: celery -A app.tasks worker -l info
    depends_on:
      - redis
      - clickhouse
    environment:
      CLICKHOUSE_URL: clickhouse://default:@clickhouse:8123/bmos
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/app
      - ./models:/app/models
    networks:
      - bmos_network

  celery-beat:
    build: ./backend
    container_name: bmos_celery_beat
    command: celery -A app.tasks beat -l info
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/app
    networks:
      - bmos_network

  mysql:
    image: mysql:8.0
    container_name: bmos_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: qbm_ai_system
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bmos_network

volumes:
  clickhouse_data:
  redis_data:
  mysql_data:

networks:
  bmos_network:
    driver: bridge

