version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: qbm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: qbm_ai
      MYSQL_USER: qbm_user
      MYSQL_PASSWORD: qbm_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - qbm-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: qbm-redis
    ports:
      - "6379:6379"
    networks:
      - qbm-network

  # 后端服务
  backend:
    build: ./backend
    container_name: qbm-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://qbm_user:qbm_password@mysql:3306/qbm_ai
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mysql
      - redis
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    networks:
      - qbm-network

  # 前端服务
  frontend:
    build: ./frontend
    container_name: qbm-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - qbm-network

volumes:
  mysql_data:

networks:
  qbm-network:
    driver: bridge