# BMOS系统 - 测试配置
# pytest配置文件

[tool:pytest]
# 测试发现
testpaths = backend/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 异步测试支持
asyncio_mode = auto

# 输出选项
addopts = 
    -v
    --tb=short
    --strict-markers
    --disable-warnings
    --color=yes

# 标记定义
markers =
    slow: 标记为慢速测试
    integration: 集成测试
    performance: 性能测试
    security: 安全测试
    unit: 单元测试
    api: API测试

# 覆盖率配置
[coverage:run]
source = backend/src
omit = 
    */tests/*
    */test_*
    */__pycache__/*
    */migrations/*
    */venv/*
    */env/*

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    if self.debug:
    if settings.DEBUG
    raise AssertionError
    raise NotImplementedError
    if 0:
    if __name__ == .__main__.:
    class .*\bProtocol\):
    @(abc\.)?abstractmethod


