-- 初始数据库架构
-- 创建数据库
CREATE DATABASE IF NOT EXISTS qbm_ai_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE qbm_ai_system;

-- 用户表
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    phone VARCHAR(20),
    is_active BOOLEAN DEFAULT TRUE,
    is_admin BOOLEAN DEFAULT FALSE,
    last_login DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_username (username),
    INDEX idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 客户表
CREATE TABLE IF NOT EXISTS customers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    customer_code VARCHAR(50) UNIQUE NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    customer_type VARCHAR(50),
    industry VARCHAR(100),
    company_size VARCHAR(50),
    contact_person VARCHAR(100),
    phone VARCHAR(20),
    email VARCHAR(100),
    address TEXT,
    city VARCHAR(50),
    province VARCHAR(50),
    country VARCHAR(50) DEFAULT '中国',
    postal_code VARCHAR(20),
    customer_value_score DECIMAL(10,2),
    customer_lifetime_value DECIMAL(15,2),
    customer_satisfaction DECIMAL(5,2),
    customer_retention_rate DECIMAL(5,2),
    status VARCHAR(20) DEFAULT 'active',
    is_vip BOOLEAN DEFAULT FALSE,
    first_contact_date DATETIME,
    last_contact_date DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_customer_code (customer_code),
    INDEX idx_customer_name (customer_name),
    INDEX idx_customer_type (customer_type),
    INDEX idx_industry (industry)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 产品表
CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_code VARCHAR(50) UNIQUE NOT NULL,
    product_name VARCHAR(200) NOT NULL,
    product_category VARCHAR(100),
    product_type VARCHAR(50),
    description TEXT,
    key_features JSON,
    technical_specs JSON,
    competitive_advantages TEXT,
    base_price DECIMAL(15,2),
    cost_price DECIMAL(15,2),
    profit_margin DECIMAL(5,2),
    pricing_strategy VARCHAR(100),
    target_market VARCHAR(200),
    market_position VARCHAR(100),
    competitive_position VARCHAR(100),
    lifecycle_stage VARCHAR(50),
    launch_date DATETIME,
    end_of_life_date DATETIME,
    quality_score DECIMAL(5,2),
    customer_satisfaction DECIMAL(5,2),
    market_share DECIMAL(5,2),
    sales_volume INT,
    revenue DECIMAL(15,2),
    status VARCHAR(20) DEFAULT 'active',
    is_featured BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_product_code (product_code),
    INDEX idx_product_name (product_name),
    INDEX idx_product_category (product_category),
    INDEX idx_product_type (product_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 合同表
CREATE TABLE IF NOT EXISTS contracts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contract_code VARCHAR(50) UNIQUE NOT NULL,
    contract_name VARCHAR(200) NOT NULL,
    contract_type VARCHAR(50),
    customer_id INT NOT NULL,
    product_id INT NOT NULL,
    user_id INT NOT NULL,
    contract_value DECIMAL(15,2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'CNY',
    payment_terms VARCHAR(200),
    delivery_terms VARCHAR(200),
    contract_terms TEXT,
    special_conditions TEXT,
    risk_assessment TEXT,
    contract_date DATETIME NOT NULL,
    effective_date DATETIME,
    expiry_date DATETIME,
    delivery_date DATETIME,
    status VARCHAR(20) DEFAULT 'draft',
    execution_progress DECIMAL(5,2) DEFAULT 0,
    invoiced_amount DECIMAL(15,2) DEFAULT 0,
    paid_amount DECIMAL(15,2) DEFAULT 0,
    outstanding_amount DECIMAL(15,2),
    risk_level VARCHAR(20),
    quality_score DECIMAL(5,2),
    customer_satisfaction DECIMAL(5,2),
    attachments JSON,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_contract_code (contract_code),
    INDEX idx_contract_name (contract_name),
    INDEX idx_customer_id (customer_id),
    INDEX idx_product_id (product_id),
    INDEX idx_user_id (user_id),
    INDEX idx_contract_date (contract_date),
    INDEX idx_status (status),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 订单表
CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_code VARCHAR(50) UNIQUE NOT NULL,
    order_name VARCHAR(200) NOT NULL,
    order_type VARCHAR(50),
    customer_id INT NOT NULL,
    product_id INT NOT NULL,
    contract_id INT,
    user_id INT NOT NULL,
    order_quantity INT NOT NULL,
    unit_price DECIMAL(15,2) NOT NULL,
    total_amount DECIMAL(15,2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'CNY',
    order_description TEXT,
    special_requirements TEXT,
    delivery_address TEXT,
    contact_info TEXT,
    order_date DATETIME NOT NULL,
    required_delivery_date DATETIME,
    actual_delivery_date DATETIME,
    completion_date DATETIME,
    status VARCHAR(20) DEFAULT 'pending',
    priority VARCHAR(20) DEFAULT 'normal',
    execution_progress DECIMAL(5,2) DEFAULT 0,
    quality_check_status VARCHAR(20),
    delivery_status VARCHAR(20),
    payment_status VARCHAR(20) DEFAULT 'unpaid',
    invoiced_amount DECIMAL(15,2) DEFAULT 0,
    paid_amount DECIMAL(15,2) DEFAULT 0,
    outstanding_amount DECIMAL(15,2),
    cost_amount DECIMAL(15,2),
    profit_amount DECIMAL(15,2),
    profit_margin DECIMAL(5,2),
    customer_satisfaction DECIMAL(5,2),
    customer_feedback TEXT,
    repeat_purchase_potential DECIMAL(5,2),
    attachments JSON,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_order_code (order_code),
    INDEX idx_order_name (order_name),
    INDEX idx_customer_id (customer_id),
    INDEX idx_product_id (product_id),
    INDEX idx_contract_id (contract_id),
    INDEX idx_user_id (user_id),
    INDEX idx_order_date (order_date),
    INDEX idx_status (status),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 财务记录表
CREATE TABLE IF NOT EXISTS financials (
    id INT AUTO_INCREMENT PRIMARY KEY,
    financial_code VARCHAR(50) UNIQUE NOT NULL,
    financial_name VARCHAR(200) NOT NULL,
    financial_type VARCHAR(50) NOT NULL,
    customer_id INT,
    product_id INT,
    contract_id INT,
    order_id INT,
    user_id INT NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'CNY',
    exchange_rate DECIMAL(10,4) DEFAULT 1.0,
    category VARCHAR(100),
    subcategory VARCHAR(100),
    account_code VARCHAR(50),
    account_name VARCHAR(100),
    transaction_date DATETIME NOT NULL,
    accounting_date DATETIME,
    due_date DATETIME,
    status VARCHAR(20) DEFAULT 'pending',
    payment_status VARCHAR(20),
    approval_status VARCHAR(20),
    description TEXT,
    reference_number VARCHAR(100),
    invoice_number VARCHAR(100),
    cost_center VARCHAR(100),
    profit_center VARCHAR(100),
    budget_category VARCHAR(100),
    variance_amount DECIMAL(15,2),
    variance_percentage DECIMAL(5,2),
    cash_flow_type VARCHAR(50),
    cash_flow_impact DECIMAL(15,2),
    tax_amount DECIMAL(15,2),
    tax_rate DECIMAL(5,2),
    tax_type VARCHAR(50),
    attachments JSON,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_financial_code (financial_code),
    INDEX idx_financial_name (financial_name),
    INDEX idx_financial_type (financial_type),
    INDEX idx_customer_id (customer_id),
    INDEX idx_product_id (product_id),
    INDEX idx_contract_id (contract_id),
    INDEX idx_order_id (order_id),
    INDEX idx_user_id (user_id),
    INDEX idx_transaction_date (transaction_date),
    INDEX idx_status (status),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
    FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE SET NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 分析结果表
CREATE TABLE IF NOT EXISTS analysis_results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    analysis_code VARCHAR(50) UNIQUE NOT NULL,
    analysis_name VARCHAR(200) NOT NULL,
    analysis_type VARCHAR(50) NOT NULL,
    user_id INT NOT NULL,
    analysis_period_start DATETIME,
    analysis_period_end DATETIME,
    analysis_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    scope_type VARCHAR(50),
    scope_value VARCHAR(200),
    data_sources JSON,
    key_findings TEXT,
    insights TEXT,
    recommendations TEXT,
    risks TEXT,
    opportunities TEXT,
    metrics JSON,
    scores JSON,
    trends JSON,
    predictions JSON,
    confidence_level DECIMAL(5,2),
    prediction_horizon INT,
    model_name VARCHAR(100),
    model_version VARCHAR(50),
    model_parameters JSON,
    model_performance JSON,
    status VARCHAR(20) DEFAULT 'completed',
    approval_status VARCHAR(20),
    is_public BOOLEAN DEFAULT FALSE,
    accuracy_score DECIMAL(5,2),
    relevance_score DECIMAL(5,2),
    actionability_score DECIMAL(5,2),
    attachments JSON,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_analysis_code (analysis_code),
    INDEX idx_analysis_name (analysis_name),
    INDEX idx_analysis_type (analysis_type),
    INDEX idx_user_id (user_id),
    INDEX idx_analysis_date (analysis_date),
    INDEX idx_status (status),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 数据导入日志表
CREATE TABLE IF NOT EXISTS data_import_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    import_code VARCHAR(50) UNIQUE NOT NULL,
    import_name VARCHAR(200) NOT NULL,
    import_type VARCHAR(50) NOT NULL,
    user_id INT NOT NULL,
    source_type VARCHAR(50),
    source_name VARCHAR(200),
    source_path VARCHAR(500),
    file_format VARCHAR(20),
    total_records INT DEFAULT 0,
    success_records INT DEFAULT 0,
    failed_records INT DEFAULT 0,
    skipped_records INT DEFAULT 0,
    duplicate_records INT DEFAULT 0,
    status VARCHAR(20) DEFAULT 'pending',
    progress_percentage DECIMAL(5,2) DEFAULT 0,
    start_time DATETIME,
    end_time DATETIME,
    duration_seconds INT,
    error_message TEXT,
    error_details JSON,
    failed_records_details JSON,
    data_quality_score DECIMAL(5,2),
    validation_results JSON,
    data_issues JSON,
    import_config JSON,
    mapping_rules JSON,
    validation_rules JSON,
    processed_data JSON,
    summary_statistics JSON,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_import_code (import_code),
    INDEX idx_import_name (import_name),
    INDEX idx_import_type (import_type),
    INDEX idx_user_id (user_id),
    INDEX idx_status (status),
    INDEX idx_start_time (start_time),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
